1 ACQUA				ACQ
2 LAVA				LAV
3 COBBLE			COB
4 GRAVEL			GHI
5 SAND				SAB
6 STONE				STO
7 LG DAY			DYE
8 NETHER W			NWR
9 DIRT				TER
10 SEED				SEM
11 SAPLING			ARB
12 IRON ORE			IOR
13 IRON ING			ING
14 IRON BUCK		SEC
15 SHEERS			FOR
16 COAL				CAR
17 IRON BLOCK 4		IBL
18 REDSTONE BLOCK 2	RBL
19 REPEATER			RRP
20 LEVER			RLV
21 CACTUS			CAC
22 LEAVES 16		FOG
23 COBBLE 4			CBS
24 LOG				LOG
25 LEATHER			PEL
26 EMERALD BLOCK	SBL

IFI iron furnace itemfr
IFA iron furnace armors
DMO diamond ore
EMO emerald ore
NUN Non unire
EPO end portal
CWB cobweb
BBR block breaker
BBS block breaker spawn
BRR block breaked

